# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-17 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uid', models.CharField(blank=True, max_length=255, null=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('last_version_sent', models.CharField(blank=True, max_length=255, null=True)),
                ('last_version_seen', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
