# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-19 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectclient_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectclient',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='projects.Project'),
        ),
    ]
