# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-20 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0009_auto_20180520_2021'),
        ('projects', '0008_auto_20180519_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectclient',
            name='last_version_sent_release_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='releases.ReleaseRule'),
        ),
    ]
