# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-22 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_projectclient_last_version_sent_release_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectclient',
            name='client_meta',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectclient',
            name='platform',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectclient',
            name='sysarch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
