# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 22:16
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_rms_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='N/A', editable=False, populate_from='name', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='rms_url',
            field=models.CharField(blank=True, help_text='Repository Management Service (Github, Bitbucket, etc)', max_length=255, null=True),
        ),
    ]
