image: python:3.6

services:
  - postgres:latest


variables:
  POSTGRES_DB: electronfission_dev


# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - ~/.cache/pip/


before_script:
  - python3 -V  # Print out python version for debugging
  # Uncomment next line if your Django app needs a JS runtime:
  # - apt-get update -q && apt-get install nodejs -yqq
  - pip3 install -r server/py-requirements/dev.txt


test:
  variables:
    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"
  script:
  - export DJANGO_CONFIGURATION=CI
  - cd server && python3 manage.py test
