image: python:3.6

services:
  - postgres

variables:
  DATABASE_HOST: postgres
  DATABASE_USER: postgres
  DATABASE_PASSWORD: ""

test:
  script:
    - export DATABASE_URL=postgres://postgres:@postgres:5432/electronfission
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r requirements.txt
    - cd server && python manage.py test
