image: python:3.6

services:
  - postgres

variables:
  DATABASE_HOST: postgres
  DATABASE_USER: postgres
  DATABASE_PASSWORD: ""

test:
  script:
    - export DATABASE_URL=postgres://postgres:@postgres:5432/electronfission
    - apt-get update -qy
    - pip3 install -r requirements.txt
    - cd server && python3 manage.py test
