# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAppBuild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('platform', models.CharField(choices=[('linux', 'linux'), ('win32', 'win32'), ('darwin', 'darwin')], max_length=10)),
                ('ci', models.CharField(choices=[('linux', 'linux'), ('win32', 'win32'), ('darwin', 'darwin')], max_length=50)),
                ('app_version', models.CharField(blank=True, max_length=50, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('commit_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('ci_job_id', models.CharField(blank=True, max_length=50, null=True)),
                ('pull_request_number', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
