# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    replaces = [('review_apps', '0001_initial'), ('review_apps', '0002_auto_20171023_1903'), ('review_apps', '0003_reviewappbuild_project'), ('review_apps', '0004_reviewappbuild_api_key'), ('review_apps', '0005_auto_20171024_1751'), ('review_apps', '0006_auto_20171025_1811')]

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAppBuild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('platform', models.CharField(choices=[('darwin', 'darwin'), ('linux32', 'linux32'), ('linux64', 'linux64'), ('win32', 'win32'), ('win64', 'win64')], max_length=10)),
                ('ci', models.CharField(choices=[('appveyor', 'appveyor'), ('travis', 'travis'), ('teamcity', 'teamcity'), ('jenkins', 'jenkins'), ('local', 'local'), ('N/A', 'N/A')], max_length=50)),
                ('app_version', models.CharField(blank=True, max_length=50, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('commit_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('ci_job_id', models.CharField(blank=True, max_length=50, null=True)),
                ('pull_request_number', models.CharField(blank=True, max_length=255, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('api_key', models.UUIDField(blank=True, null=True)),
                ('build_url', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
