# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewappbuild',
            name='ci',
            field=models.CharField(choices=[('appveyor', 'appveyor'), ('travis', 'travis'), ('teamcity', 'teamcity'), ('jenkins', 'jenkins')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reviewappbuild',
            name='platform',
            field=models.CharField(choices=[('darwin', 'darwin'), ('linux32', 'linux32'), ('linux64', 'linux64'), ('win32', 'win32'), ('win64', 'win64')], max_length=10),
        ),
    ]
