# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_apps', '0003_remove_reviewappbuild_branch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewappbuild',
            name='platform',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
