# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_apps', '0004_reviewappbuild_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewappbuild',
            name='build_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reviewappbuild',
            name='api_key',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
