# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-17 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='release',
            old_name='darwin_artifact',
            new_name='darwin_dmg',
        ),
        migrations.AddField(
            model_name='release',
            name='darwin_zip',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
