# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-17 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_created_by'),
        ('releases', '0003_releaserule'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaserule',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
