# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-17 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0004_releaserule_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='darwin_dmg_sha512',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='darwin_zip_sha512',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='releaserule',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='release_rules', to='projects.Project'),
        ),
    ]
