# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-19 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20180519_1942'),
        ('releases', '0005_auto_20180517_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.ProjectClient')),
                ('release_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='releases.ReleaseRule')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
