# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-19 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0006_releasemember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='releasemember',
            old_name='client',
            new_name='project_client',
        ),
    ]
