# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-20 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0008_releasemember_is_rolled_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasemember',
            name='release_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='releases.ReleaseRule'),
        ),
    ]
