# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-02 16:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth0authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth0loginprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
