# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('review_apps', '0002_auto_20171023_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewappbuild',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
