# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('review_apps', '0003_reviewappbuild_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewappbuild',
            name='api_key',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
